/**
 * Embed frontend build artifacts into the Worker.
 * Run AFTER `npm run build` in frontend/.
 * Generates src/frontend-assets.ts with inline content strings.
 */
import { readFileSync, writeFileSync, readdirSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const distDir = resolve(__dirname, '../../frontend/dist');
const outFile = resolve(__dirname, '../src/frontend-assets.ts');

// Read built files
const indexHtml = readFileSync(resolve(distDir, 'index.html'), 'utf-8');

// Find the JS asset in assets/ directory
const assets = readdirSync(resolve(distDir, 'assets'));
let mainJs = '';
let mainJsName = '';
for (const f of assets) {
  if (f.endsWith('.js')) {
    mainJs = readFileSync(resolve(distDir, 'assets', f), 'utf-8');
    mainJsName = f;
    break;
  }
}

const content = `// Auto-generated by embed-assets.ts — do not edit manually
// Generated from frontend/dist/ build output

export const FRONTEND_HTML = ${JSON.stringify(indexHtml)};

export const FRONTEND_JS_NAME = ${JSON.stringify(mainJsName)};

export const FRONTEND_JS_CONTENT = ${JSON.stringify(mainJs)};
`;

writeFileSync(outFile, content, 'utf-8');
console.log(`✅ Generated ${outFile}`);
console.log(`   HTML: ${indexHtml.length} bytes`);
console.log(`   JS:   ${mainJsName} (${mainJs.length} bytes)`);
